language: python # => 1
    python: # => 2
      - "3.5"
      - "3.6"
    services: # => 3
      - postgresql
    env: # => 4
      -DJANGO=2.1 DB=mysql
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
    script: # => 7
      - python manage.py test
