# Generated by Django 2.1.2 on 2019-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='base_image',
            field=models.ImageField(null=True, upload_to='media/interest/'),
        ),
    ]
