# Generated by Django 2.1.7 on 2019-03-24 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190323_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='base_image',
            field=models.ImageField(blank=True, upload_to='media/interest/'),
        ),
        migrations.AddField(
            model_name='interest',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_interest_related_topics_+', to='blog.interest'),
        ),
        migrations.RemoveField(
            model_name='blog',
            name='interests',
        ),
        migrations.AddField(
            model_name='blog',
            name='interests',
            field=models.ForeignKey(blank=True, default='0', on_delete=django.db.models.deletion.CASCADE, to='blog.interest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interest',
            name='interest_name',
            field=models.TextField(),
        ),
    ]
