# Generated by Django 2.1.7 on 2019-04-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_interest_related_intrests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='related_intrests',
            field=models.ManyToManyField(blank=True, related_name='_interest_related_intrests_+', to='blog.interest'),
        ),
    ]
