# Generated by Django 2.1.7 on 2019-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.TextField(default='shc'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interest',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
