# Generated by Django 2.1.2 on 2019-04-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190406_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/interest/'),
        ),
    ]
