# Generated by Django 2.1.7 on 2019-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190407_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
