# Generated by Django 2.1.7 on 2019-04-13 16:45

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20190411_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.TextField(blank=True, null=True)),
                ('heading', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('delete_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interests', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.interest')),
            ],
        ),
    ]
