# Generated by Django 2.1.7 on 2019-05-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile1',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='profile1',
            name='user',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='profile1',
        ),
    ]
