# Generated by Django 2.1.7 on 2019-05-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20190501_0618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
    ]
