# Generated by Django 2.1.7 on 2019-05-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('registration', '0005_remove_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, to='blog.Blog'),
        ),
    ]
